---
- name: Promote the Content View to a Life Cycle Environment
  hosts: tag_Name_satellite01
  connection: local

  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - current_lce is defined
          - target_lce is defined
          - satellite_admin_username is defined
          - satellite_admin_passwd is defined
          - satellite_organization is defined
          - satellite_content_view is defined
          - satellite_cv_end_date is defined

        fail_msg: "Required variables not set"

    - name: "Promote the Content View new version from {{ current_lce }} to {{ target_lce }}"
      redhat.satellite.content_view_version:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_passwd }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ satellite_organization }}"
        content_view: "{{ satellite_content_view }}"
        description: "Publishment-{{ satellite_cv_end_date }}"
        current_lifecycle_environment: "{{ current_lce }}"
        lifecycle_environments: "{{ target_lce }}"
        validate_certs: false
