---
- name: Publish a new version of the configured Content View
  hosts: tag_Name_satellite01
  connection: local

  tasks:
    - name: Fail if variables not defined
      ansible.builtin.assert:
        that:
          - satellite_admin_username is defined
          - satellite_admin_passwd is defined
          - satellite_organization is defined
          - satellite_content_view is defined
          - satellite_cv_end_date is defined

        fail_msg: "Required variables not set"

    - name: "Update the Content View Filter Rule"
      redhat.satellite.content_view_filter_rule:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_passwd }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ satellite_organization }}"
        content_view: "{{ satellite_content_view }}"
        content_view_filter: "ErrataByDate"
        date_type: updated
        types: "{{ satellite_content_view_filter_types }}"
        end_date: "{{ satellite_cv_end_date }}"
        validate_certs: false

    - name: "Publish the new version of Content View to Library"
      redhat.satellite.content_view_version:
        username: "{{ satellite_admin_username }}"
        password: "{{ satellite_admin_passwd }}"
        server_url: "https://{{ inventory_hostname }}"
        organization: "{{ satellite_organization }}"
        content_view: "{{ satellite_content_view }}"
        description: "Publishment-{{ satellite_cv_end_date }}"
        lifecycle_environments:
          - Library
        validate_certs: false
